# Generated by Django 5.1.7 on 2025-05-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_userroles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroles',
            name='role',
            field=models.CharField(choices=[('DEV', 'Developer'), ('QA', 'QA Engineer'), ('MGR', 'Manager'), ('DOM', 'Domain Expert')], default=None, max_length=3),
        ),
    ]
