# Generated by Django 5.1.7 on 2025-06-03 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_alter_userroles_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.CharField(choices=[('A_first', 'Baseline first → then SHAP'), ('B_first', 'SHAP first → then Baseline')], help_text='A_first means scenarios 1–3 are Baseline and 4–6 are SHAP. B_first means scenarios 1–3 are SHAP and 4–6 are Baseline.', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_time_ms', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_number', models.PositiveSmallIntegerField(help_text='Integer 1..6; first block of 3 is Block A, last 3 is Block B.')),
                ('decision_key', models.CharField(help_text="Identifier of the chosen decision, e.g. 'immediate', 'testing', etc.", max_length=50)),
                ('confidence', models.PositiveSmallIntegerField(help_text='Confidence rating (1..7).')),
                ('time_spent_ms', models.BigIntegerField(help_text='Milliseconds elapsed from scenario display → submit.')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='Frontend.studysession')),
            ],
            options={
                'ordering': ['session', 'scenario_number'],
                'unique_together': {('session', 'scenario_number')},
            },
        ),
    ]
